# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\python\compare_prices\GUI\programs.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.setWindowModality(QtCore.Qt.ApplicationModal)
        Window.resize(969, 847)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(7)
        sizePolicy.setHeightForWidth(Window.sizePolicy().hasHeightForWidth())
        Window.setSizePolicy(sizePolicy)
        Window.setMinimumSize(QtCore.QSize(969, 847))
        Window.setMaximumSize(QtCore.QSize(969, 847))
        Window.setMouseTracking(False)
        Window.setTabletTracking(False)
        Window.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon2.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        Window.setWindowIcon(icon)
        Window.setToolTip("")
        Window.setStyleSheet("QRadioButton {color: rgb(128, 128, 128);}")
        Window.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(Window)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 0, 191, 41))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 500, 256, 61))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(104, 203, 253);\n"
"    font: 75 12pt \"Tahoma\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 170, 255);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(460, 0, 291, 41))
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(280, 500, 681, 61))
        self.pushButton_2.setToolTip("")
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    \n"
"    \n"
"    background-color: rgb(0, 198, 145);\n"
"    font: 75 12pt \"Tahoma\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 209, 153);\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 580, 951, 71))
        self.progressBar.setStyleSheet("")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 670, 951, 121))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 75 20pt \"Tahoma\";\n"
"color: rgb(0, 170, 255);\n"
"text-align:center;")
        self.label_3.setObjectName("label_3")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 40, 256, 301))
        self.listWidget.setObjectName("listWidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(280, 40, 681, 361))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.Left = QtWidgets.QRadioButton(self.centralwidget)
        self.Left.setGeometry(QtCore.QRect(400, 430, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Left.setFont(font)
        self.Left.setStyleSheet("")
        self.Left.setChecked(True)
        self.Left.setObjectName("Left")
        self.Inner = QtWidgets.QRadioButton(self.centralwidget)
        self.Inner.setGeometry(QtCore.QRect(690, 440, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Inner.setFont(font)
        self.Inner.setObjectName("Inner")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 370, 256, 31))
        self.comboBox.setObjectName("comboBox")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 440, 256, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 350, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 410, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 969, 26))
        self.menubar.setObjectName("menubar")
        Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Window)
        self.statusbar.setObjectName("statusbar")
        Window.setStatusBar(self.statusbar)

        self.retranslateUi(Window)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "Maruschak Technology v2.1      Telegram: @dataskill"))
        self.label.setText(_translate("Window", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Список файлов</span></p></body></html>"))
        self.pushButton.setText(_translate("Window", "Загрузить файлы"))
        self.label_2.setText(_translate("Window", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Предварительный просмотр</span></p></body></html>"))
        self.pushButton_2.setText(_translate("Window", "Обработать"))
        self.label_3.setText(_translate("Window", "<html><head/><body><p><br/></p></body></html>"))
        self.Left.setToolTip(_translate("Window", "<html><head/><body><p><span style=\" font-family:\'Verdana\',\'sans-serif\'; font-size:15px; font-weight:400; color:#000000; background-color:#ffffff;\">LEFT возвращает все записи из левой таблицы (table1) и соответствующие записи из правой таблицы (table2)</span></p></body></html>"))
        self.Left.setText(_translate("Window", "Left"))
        self.Inner.setToolTip(_translate("Window", "<html><head/><body><p><span style=\" font-family:\'Verdana\',\'Geneva\',\'sans-serif\'; font-size:16px; font-weight:400; color:#222222; background-color:#ffffff;\">INNER объединяются только те значения, которые можно найти в обеих таблицах</span></p></body></html>"))
        self.Inner.setText(_translate("Window", "Inner"))
        self.label_4.setText(_translate("Window", "Выбирите главный файл"))
        self.label_5.setText(_translate("Window", "Укажите имя сохраняемого файла"))
import img_rc
